### ISSUE TITLE
face_alignment dependency issue for `extract_kp_videos.py`

### ISSUE THREAD

**Issue by SCZwangxiao** [RenYurui/PIRender#30]
I've solved this problem, and this issue serves as a reminder for others.

If you are using `face_alignment==1.4.0`, an `AttributeError` will occur when running `extract_kp_videos.py`:

```bash
Total number of videos: 36237
0it [00:00, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/mnt3/xiao.wang/PIRender/Deep3DFaceRecon_pytorch/extract_kp_videos.py", line 69, in run
    kp_extractor = KeypointExtractor()
  File "/mnt3/xiao.wang/PIRender/Deep3DFaceRecon_pytorch/extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D)
  File "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.6/enum.py", line 326, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "extract_kp_videos.py", line 98, in <module>
    for data in tqdm(pool.imap_unordered(run, zip(filenames, args_list, device_ids))):
  File "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.6/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AttributeError: _2D
```

To solve this problem, downgrade `face_alignment` to `1.3.0`.

**Comment by MMMDY** [comment]
你好，我运行遇到extract_kp_videos.py时报错: all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! 我已经指定参数--device_ids=0使用单个gpu仍然报错，您能帮助我吗，非常感谢！完整的错误如下：
![image](https://github.com/RenYurui/PIRender/assets/95173494/768e7325-d41e-43f7-80b4-c8cd89970c78)

**Comment by ZayneHuang** [comment]
> 你好，我运行遇到extract_kp_videos.py时报错: all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! 我已经指定参数--device_ids=0使用单个gpu仍然报错，您能帮助我吗，非常感谢！完整的错误如下： ![image](https://user-images.githubusercontent.com/95173494/252360663-768e7325-d41e-43f7-80b4-c8cd89970c78.png)

Hi @MMMDY , I encountered the same problem and found that this error is caused by the `face_alignment` package. 

The recommended version of `face_alignment` by PIRender is 1.3.0, where the `batch_detect` function of sfd is written as `img_batch = img_batch - torch.Tensor([104, 117, 123]).view(1, 3, 1, 1)` (in `face_alignment/detection/sfd/detect.py`). The `img_batch ` tensor is on the CUDA device, while the other is on the CPU.  

To resolve this issue, just modify the code to `img_batch = img_batch - torch.Tensor([104, 117, 123]).view(1, 3, 1, 1).to(device)` (refer the latest version of the `face_alignment` package: [link](https://github.com/1adrianb/face-alignment/blob/master/face_alignment/detection/sfd/detect.py)).  After making this change, the issue should be resolved.
